{% set name = "epiweeks4cf" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:

  url: https://pypi.io/packages/source/{{ name[0] }}/epiweeks/epiweeks-{{ version }}.tar.gz
  sha256: e6f6de0952b36b7dd50d2a2eed7937f654cc50823329664d333ee753bbc5d026

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=51
    - pip
  run:
    - python >=3.7

test:
  imports:
    - epiweeks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dralshehri/epiweeks
  summary: Epidemiological weeks calculation based on the US CDC (MMWR) and ISO week numbering systems
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jdhughes-usgs
